version: '3.3'
services:
  postgresqldb:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5632:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
